cratespawning:
  spawncrates: true
  interval: 300
  radius: 1000
  broadcastCrates: true
treefeller:
  maxblocks: 256
  speed: 3
  trees: true
  mushrooms: true
transmogrifier:
  maxblocks: 64
  speed: 3
terramorpher:
  size: 2
giga_drill_breaker:
  size: 1