name: LootCrate
version: 1.0
author: Maurdekye
main: com.ncolaprete.lootcrate.LootCrate
depend: [Essentials]

commands:
  buykey:
    description: buys the given key.
    usage: /buykey <type> [amount]
    permission: lootcrate.buykey
    permission-message: You do not have permission to buy crate keys.
  givekey:
    description: gives a crate key of the given type and amount to the given player.
    usage: /givekey <type> [amount] [player]
    permission: lootcrate.givekey
    permission-message: You do not have permission to give yourself crate keys.
  givecrate:
    description: gives you or a given player a crate of the given type.
    usage: /givecrate <type> [amount] [player]
    permission: lootcrate.givecrate
    permission-message: You do not have permission to give yourself crates.
  givereward:
    description: gives reward of the designated type and amount to yourself. Look at a chest to use.
    usage: /givereward <type> [amount]
    permission: lootcrate.givereward
    permission-message: You do not have permission to spawn crate rewards.

permissions:
  lootcrate.buykey:
    default: true
  lootcrate.givekey:
    default: op
  lootcrate.givecrate:
    default: op
  lootcrate.givereward:
    default: op
  lootcrate.opencrate:
    description: Allows the user to view and unlock loot crates
    default: true
