name: WordGuesser
version: 1.0
author: Maurdekye
main: com.ncolaprete.wordguesser.Main
commands:
  startgame:
    description: Start the guessing game
    usage: /startgame
  stopgame:
    description: Stop the guessing game
    usage: /stopgame