name: LootCrate
version: 1.0
author: Maurdekye
main: com.ncolaprete.lootcrate.LootCrate
depend: [Essentials]

commands:
  givekey:
    description: gives a crate key of the given type to the given player.
    usage: /givekey <type> [player]
    permission: lootcrate.givekey
    permission-message: You do not have permission to give yourself crate keys.
  givecrate:
    description: gives you or a given player a crate of the given type.
    usage: /givecrate <type> [player]
    permission: lootcrate.givecrate
    permission-message: You do not have permission to give yourself crates.
  spawncrate:
    description: spawns a loot crate of the designated type at your cursor.
    usage: /spawncrate <type>
    permission: lootcrate.spawncrate
    permission-message: You do not have permission to spawn crates.
  givereward:
    description: gives reward of the designated type and amount to yourself. Look at a chest to use.
    usage: /givereward <type> [amount]
    permission: lootcrate.givereward
    permission-message: You do not have permission to spawn crate rewards.

permissions:
  lootcrate.givekey:
    default: op
  lootcrate.givecrate:
    default: op
  lootcrate.spawncrate:
    default: op
  lootcrate.givereward:
    default: op
  lootcrate.opencrate:
    description: Allows the user to view and unlock loot crates
    default: true
